CREATE PUBLIC.SEQUENCE ADDRESS_SEQ;


CREATE TABLE ADDRESS (
	id bigint GENERATED BY DEFAULT AS SEQUENCE ADDRESS_SEQ PRIMARY KEY,
	CellPhoneNumber varchar(100),
	name varchar(100),
	email varchar(100),
	birthday varchar(100)
);